/* Warning: This file is generated by /data/home/olly/tmp/xapian-git-snapshot/tags/v1.2.20/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_sortfunctor1();
extern bool test_sortfunctor2();
extern bool test_changesorter1();
extern bool test_sortfunctorempty1();
extern bool test_multivaluekeymaker1();
extern bool test_sortfunctorremote1();
