/* Warning: This file is generated by /data/home/olly/tmp/xapian-git-snapshot/tags/v1.2.20/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_badtransaction1();
extern bool test_committransaction1();
extern bool test_canceltransaction1();
extern bool test_canceltransaction2();
