/* Warning: This file is generated by /data/home/olly/tmp/xapian-git-snapshot/tags/v1.2.20/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_tradweight3();
extern bool test_bm25weight3();
extern bool test_bm25weight4();
extern bool test_bm25weight5();
extern bool test_checkinitweight1();
extern bool test_checkstatsweight1();
