/* Warning: This file is generated by /data/home/olly/tmp/xapian-git-snapshot/tags/v1.2.20/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_replicate1();
extern bool test_replicate2();
extern bool test_replicate3();
extern bool test_replicate4();
extern bool test_replicate5();
extern bool test_replicate6();
