/* Warning: This file is generated by /data/home/olly/tmp/xapian-git-snapshot/tags/v1.2.20/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_metadata1();
extern bool test_metadata2();
extern bool test_metadata3();
extern bool test_metadata4();
extern bool test_metadata5();
extern bool test_writeread1();
