/* Warning: This file is generated by /data/home/olly/tmp/xapian-git-snapshot/tags/v1.2.20/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_matchspy1();
extern bool test_matchspy2();
extern bool test_matchspy4();
extern bool test_matchspy5();
extern bool test_matchspy6();
