/* Warning: This file is generated by /data/home/olly/tmp/xapian-git-snapshot/tags/v1.2.20/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_externalsource1();
extern bool test_externalsource2();
extern bool test_externalsource3();
extern bool test_externalsource4();
extern bool test_valueweightsource1();
extern bool test_valueweightsource2();
extern bool test_valueweightsource3();
extern bool test_fixedweightsource1();
extern bool test_changemaxweightsource1();
extern bool test_emptyvalwtsource1();
