/** @file allsnowballheaders.h
 *  @brief Include the headers for all the snowball stemmers.
 */
/* Warning: This file is generated by languages/generate-allsnowballheaders - do not modify directly! */
/* Copyright (C) 2007 Olly Betts
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
 */

#ifndef XAPIAN_INCLUDED_ALLSNOWBALLHEADERS_H
#define XAPIAN_INCLUDED_ALLSNOWBALLHEADERS_H

#include "danish.h"
#include "dutch.h"
#include "english.h"
#include "finnish.h"
#include "french.h"
#include "german.h"
#include "german2.h"
#include "hungarian.h"
#include "italian.h"
#include "kraaij_pohlmann.h"
#include "lovins.h"
#include "norwegian.h"
#include "porter.h"
#include "portuguese.h"
#include "romanian.h"
#include "russian.h"
#include "spanish.h"
#include "swedish.h"
#include "turkish.h"

#define LANGSTRING "danish dutch english finnish french german german2 hungarian italian kraaij_pohlmann lovins norwegian porter portuguese romanian russian spanish swedish turkish"

#endif // XAPIAN_INCLUDED_ALLSNOWBALLHEADERS_H
